# Generated by Django 5.2.15 on 2026-07-07 08:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_equipment_broken_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=200, verbose_name='borrower name')),
                ('borrower_phone', models.CharField(max_length=30, verbose_name='borrower phone')),
                ('due_date', models.DateField(verbose_name='due date')),
                ('details', models.TextField(blank=True, verbose_name='details')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='returned at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('responsible', models.ForeignKey(help_text='Staff member who handed out this loan.', on_delete=django.db.models.deletion.PROTECT, related_name='loans_given', to=settings.AUTH_USER_MODEL, verbose_name='responsible')),
                ('returned_by', models.ForeignKey(blank=True, help_text='Staff member who processed the return. Set automatically once all equipment is returned.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans_returned', to=settings.AUTH_USER_MODEL, verbose_name='returned by')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('quantity_returned', models.PositiveIntegerField(default=0, verbose_name='quantity returned')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_items', to='inventory.equipment', verbose_name='equipment')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='loans.loan', verbose_name='loan')),
            ],
            options={
                'verbose_name': 'loan item',
                'verbose_name_plural': 'loan items',
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='loanitem_quantity_gte_one'), models.CheckConstraint(condition=models.Q(('quantity_returned__lte', models.F('quantity'))), name='loanitem_quantity_returned_lte_quantity'), models.UniqueConstraint(fields=('loan', 'equipment'), name='loanitem_unique_loan_equipment')],
            },
        ),
    ]
