# Generated by Django 5.2.15 on 2026-07-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_equipment_broken_quantity'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitem',
            name='quantity_broken',
            field=models.PositiveIntegerField(default=0, help_text='How many of the returned quantity came back broken.', verbose_name='quantity broken'),
        ),
        migrations.AddConstraint(
            model_name='loanitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_broken__lte', models.F('quantity_returned'))), name='loanitem_quantity_broken_lte_quantity_returned'),
        ),
    ]
