# Generated by Django 5.2.15 on 2026-07-09 08:24

import django.core.validators
import re
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanitem_quantity_broken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='borrower_phone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^(\\+358\\d{6,12}|0\\d{6,12})$'), 'Enter a valid phone number, e.g. 0401234567 or +358401234567.')], verbose_name='borrower phone'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('borrower_name__contains', ' ')), name='loan_borrower_name_has_space'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('returned_at__isnull', True), ('returned_by__isnull', True)), models.Q(('returned_at__isnull', False), ('returned_by__isnull', False)), _connector='OR'), name='loan_returned_fields_consistent'),
        ),
    ]
