# Generated by Django 5.2.15 on 2026-07-07 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('short_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_external_loanable', models.BooleanField(default=False, help_text='If unset, only club members can borrow this equipment.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.category')),
            ],
            options={
                'verbose_name_plural': 'equipment',
                'ordering': ['name'],
            },
        ),
    ]
