# Generated by Django 5.2.15 on 2026-07-07 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_equipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'equipment', 'verbose_name_plural': 'equipment'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_external_loanable',
            field=models.BooleanField(default=False, help_text='If unset, only club members can borrow this equipment.', verbose_name='external loanable'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total number in stock. Must be 1 for equipment with a short code.', verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='short_code',
            field=models.CharField(blank=True, help_text='Identifies one specific physical item, e.g. X75. Leave blank for equipment tracked only as a stock count (see quantity).', max_length=20, null=True, unique=True, verbose_name='short code'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('short_code__isnull', True), ('quantity', 1), _connector='OR'), name='equipment_short_code_implies_quantity_one'),
        ),
    ]
