# Generated by Django 5.2.15 on 2026-07-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_short_code_quantity_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='broken_quantity',
            field=models.PositiveIntegerField(default=0, help_text='How many of this equipment are currently broken and unavailable for loan.', verbose_name='broken quantity'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('broken_quantity__lte', models.F('quantity'))), name='equipment_broken_quantity_lte_quantity'),
        ),
    ]
