# Generated by Django 5.2.15 on 2026-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_equipment_broken_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo shown in the storage detail view.', upload_to='equipment/', verbose_name='image'),
        ),
    ]
