# Generated by Django 5.2.15 on 2026-07-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forces the user to change their password on next login. Set automatically when an admin creates the account or resets its password.', verbose_name='must change password'),
        ),
    ]
