# Generated by Django 5.2.17 on 2026-09-14 06:19

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(re.compile('^(\\+358\\d{6,12}|0\\d{6,12})$'), 'Enter a valid phone number, e.g. 0401234567 or +358401234567.')], verbose_name='phone'),
        ),
    ]
