# Generated by Django 5.2.17 on 2026-09-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whats_new_seen_version',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
